config/routes.rb
ArticleApp::Application.routes.draw do
  resources :animals

  get "sessions/new"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  get "articles/welcome"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :sessions
  get "log_out" => "sessions#destroy", :as => "log_out"
  match 'list_articles', :to => 'articles#index', :as => "show_article_list"

  resources :home
  resources :comments
  resources :articles  do
    collection do
      get 'my_method_1'
    end
    member do
      get 'my_method_2'
    end
  end

  namespace :admin do
    resources :articles
  end
  root :to => 'sessions#new'
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :content, :pages_count ,:user_id, :rating
  validates :title, :presence => true,
    :length => { :minimum => 3, :maximum => 20, },
    :format => {:with => /[a-zA-Z\s]+$/}, 
    :uniqueness => {:message => " tidak boleh sama"},
    :allow_blank => false
  #validates :title , :inclusion => { :in => %w(wgs kiranatama), :message => "%{value} must be 'wgs' or 'kiranatama'" }
  # validates :title, :exclusion => { :in => %w(www http https), :message => "%{value} is reserved." }
  
  
  #validates :pages_count, :numericality => true
  #validates :pages_count, :presence => true , :unless => "content == 'content'"

  validate :valid_content
  validates :pages_count, :presence => true, :unless => "title == 'visca'"
  validates :title, :presence => true, :on => :save # ==> validates on both create and update
  #validates :title, :presence => true, :on => :create # ==> validates on create
  #validates :title, :presence => true, :on => :update # ==> validates on update

  belongs_to :user
  belongs_to :writer,
    :class_name => "User",
    :foreign_key => "user_id"
 
  
  #deklarasi many to many relationship
  has_many :articles_has_categories
  has_many :categories , :through => :articles_has_categories
  has_many :comments , :dependent => :destroy 
  #------------------------------------
  has_many :valid_comments,
    :class_name => "Comment" ,
    :foreign_key => "article_id"
  scope :pages_count, where("pages_count > 0")
  scope :create_after_day, lambda {|time| where("created_at > ?", time) }
  scope :create_before_day, lambda {|time| where("created_at < ?", time) }
  scope :share_article, where("title like '%a%'")
  #scope :my_country, where("title like '%S%'")
  scope :create_after_time, lambda {|time| where("created_at > ?", time) }
  default_scope where("user_id is not null and title is not null")

  scope :have_user, lambda { |user| where("user_id = ?", user) }

  def valid_content
    self.errors[:content] << " is too short, brooo !!" if content.length < 3
  end

  #def self.search_by_title(params_title)
  #  Article.find_all_by_title(params_title)
  #end
  
  #Class method
  def self.hundred_char
    self.where("LENGTH(title) > 3")
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #layout 'articles'
  before_filter :find_article, :except => [:index, :create, :new, :my_method_1, :welcome]
  before_filter :require_login, :only => [:new, :create, :edit, :update, :delete]
  
  $nama_var = "global variable"
  
  def welcome
    render :text => "This is Welcome Text"
  end
  
  def index
    @articles = Article.all
    #ap @articles
    #session['session_name'] = "sample for saving to session"

    #lazy loading
#    articles = Article.all
#    articles.each do |a|
#      puts a.user.email
#    end

    #pre loading
#    articles = Article.includes("user")
#    articles.each do |b|
#      puts b.user.email
#    end
   # render :layout => 'false
  end

  #view for new article
  def new
    @article = Article.new
  end

  #view for edit article
  def edit;end

  #create new article
  def create
    #debugger
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = 'Article was successfully created.'
      redirect_to :controller => :users, :action => :index
      #redirect_to :controller => :users, :action => :new
    else
      flash[:error] = "Article was failed created"
      render :action => :new
    end
  end

  #show article detail
  def show
    @comment = Comment.new
    @comments = @article.comments
    if @article.nil?
      flash[:notice] = 'Article was not found.'
      redirect_to articles_path
    end
  end

  # update an article
  def update
    if @article.update_attributes(params[:article])
      flash[:notice] = 'Article was successfully updated.'
      redirect_to articles_path#(:dari_update => "update")
      # redirect_to :controller => :articles, :action => :index #articles_path # :alert => "sucess"
      #redirect_to :controller => :home, :action => :index #, :alert => 'This is a flash alert'
    else
      flash[:notice] = "Article was failed updated"
      render :action => "edit"
    end
  end

  #delete an article
  def destroy
    if @article.destroy
      flash[:error] = "Article was successfully deleted"
    else
      flash[:notice] = "Article was failed deleted"
    end
    redirect_to articles_path
  end

  def my_method_1
  end
  
  def my_method_2
  end

  
  private
  def find_article
    @article = Article.find(params[:id])
  end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comments.html.erb
<%unless @comments.empty?%>
  <% @comments.each do |comment| %>
    <ul>
      <li> <%= comment.content %><br /></li>
    </ul>
  <% end %>
<%else%>
  <h5>-- No comments here --</h5>
<% end %>

app/views/articles/articles.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticleApp</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>    
    <%= yield %>
<h2>My Articles Layout</h2
  </body>
</html>

app/views/articles/edit.html.erb
<h3>Edit Article</h3>
<%= flash[:notice] %>
<% if @article.errors.any? %>
  <div id="errorExplanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%=form_for(@article, :url => article_path, :html => {:method => :put}) do |f|%>
  <%=f.label :title%>
  <%=f.text_field :title%>
  <p/>
  <%=f.label :content%>
  <p/>
  <%=f.text_area :content%>
  <p/>
  <%= f.label :pages_count %> :
  <%=f.text_field :pages_count%>
  <p/>
  <%=f.submit :update, :id => "update_button"%>
  <p/>
  <%=link_to "Back", articles_path, :id => "link_back"%>
<%end%>

app/views/articles/index.html.erb
<%= flash[:notice] %>
<h3>List of articles :</h3>
<div id="header">
  <table width="30%" border="">
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3">Action</th>
    </tr>
    <%@articles.each do |x|%>
      <tr>
        <td><div class="menu"><%= x.title %></div></td>
        <td><%= x.content %></td>
        <td><%= link_to "Edit", edit_article_path(x.id) %></td>
        <td><%= link_to "Show" , article_path(x) %>  <%#= link_to "Show" , show_article_path(x) %></td>
        <td><%= link_to 'Destroy', article_path(x.id), :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <%end%>
  </table>
</div>
<p/>
<%= link_to "New Articles", new_article_path %>
<%= @article    %>
<br />
<%#= link_to "call my_method_1", my_method_1_articles_path %>

<%#= raw(list_articles) %>

<%#= params[:dari_destroy] %>
<%#= params[:dari_update] %>
<p><%#= session['session_name']%></p>

app/views/articles/new.html.erb
<h3>New Article</h3>
<%= flash[:notice] %>
<%= flash[:error] %>
<% if @article.errors.any? %>
  <div id="errorExplanation">
    <h2>
      <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%#= @article.errors.full_messages if @article.errors %>

<%=form_for @article do |f| %>
  <%= f.label :title %> :
  <%= f.text_field :title %>
  <p/>
  <%=f.label :content%> :
  <p/>
  <%=f.text_area :content, :rows => 5%>
  <p/>
  <%= f.label :pages_count %> :
  <%=f.text_field :pages_count%>
  <p/>
  <%= hidden_field :article, :user_id, :value => current_user.id %>

  <%=f.submit :create%>
  <p/>
  <%=link_to "Back", articles_path%>
  <p />
  <%#= f.hidden_field :user_id %>
  <%#= text_field_tag :my_name  %>
<%end%>


<%= link_to "Back to Index",show_article_list_path %>
<%#= "FORM TAG" %>

<%#= form_tag articles_path do -%>
  <%#= text_field_tag "article", "firstname" %>
<%# end -%>

app/views/articles/show.html.erb
<h3>Detail Article</h3>
<p />
Title  :  <%=@article.title%>
<p />
Content  :
<%=@article.content%>
<p/>
<hr />
<div>
  <%= form_for @comment, :url => comments_path, :remote => true do |f| %>
    <%= f.text_area :content , :rows => 5%>
    <%= f.hidden_field :article_id, :value => @article.id %>
    <br />
    <%= submit_tag "comment" %>
  <% end %>
</div>
<h2>List of Comment</h2>
<div id="comments">  
  <%unless @comments.nil?%>
    <%= render :partial => "comments", :locals => {:comments => @comments}  %>
  <%end%>
</div>
<br /><br />
<%=link_to "Back", articles_path, :id => 'link_back'%>